server:
  port: ${CONFIG_SERVER_PORT}

spring:
  cloud:
    config:
      server:
        git :
          uri: https://github.com/karoonakar/Spring-cloud-${ENV_TYPE}
        encrypt:
          enabled: false
security:
  basic:
    enabled: true
  user:
    name: user
    password: c91c4f9724e29dec371a8efa5e33b2a37e4c119486234d0a127e6d7816c0d7fa
---
spring:  
  profiles: dev
server:  
  port: ${CONFIG_SERVER_PORT}